version: "3.8"

services:

  oteapi:
    container_name: oteapi
    # image: ghcr.io/emmc-asbl/oteapi:1.20240301.346
    image: ghcr.io/emmc-asbl/oteapi:latest
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      OTEAPI_REDIS_TYPE: redis
      OTEAPI_REDIS_HOST: redis
      OTEAPI_REDIS_PORT: 6379
      OTEAPI_prefix: "${OTEAPI_prefix:-/api/v1}"   
      # OTEAPI_PLUGIN_PACKAGES: 'git+https://github.com/SINTEF/oteapi-dlite-Mod@master' # NOTE! Branch under development
      OTEAPI_PLUGIN_PACKAGES: "-v -e /oip-oteapi-plugins"
      # OTEAPI_PLUGIN_PACKAGES: pip install oteapi-dlite --index-url https://__token__:94sCwogRr4fXvdcsz8ix@gitlab.cc-asp.fraunhofer.de/api/v4/projects/55581/packages/pypi/simple

    volumes:
      - "../oip-oteapi-plugins:/oip-oteapi-plugins"
      - "./entities:/entities"
      - "./output:/output"

  redis:
    container_name: redis
    image: redis:latest
