version: "3.8"

services:

  oteapi:
    image: ghcr.io/emmc-asbl/oteapi:1.20240301.346
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      OTEAPI_REDIS_TYPE: redis
      OTEAPI_REDIS_HOST: redis
      OTEAPI_REDIS_PORT: 6379
      OTEAPI_prefix: "${OTEAPI_prefix:-/api/v1}"   
      OTEAPI_PLUGIN_PACKAGES: git+https://github.com/EMMC-ASBL/oteapi-dlite@hotfix/remove-session/mapping-fuseki#egg=oteapi-dlite # NOTE! Branch under development
    volumes:
      - "./entities:/entities"
      - "./output:/output"
      - "./config/entrypoint.sh:/app/entrypoint.sh"

  fuseki:
    image: secoresearch/fuseki
    ports:
      - "3030:3030"
    environment:
      ENABLE_DATA_WROTE: true
      ENABLE_UPLOAD: true
      ENABLE_UPDATE: true
      QUERY_TIMEOUT: 5000
    volumes:
      - "fusekidata:/fuseki-base/databases"
      - "./config/shiro.ini:/jena-fuseki/shiro.ini"
      - "./config/otedemo.ttl:/fuseki-base/configuration/otedemo.ttl"

  redis:
    image: redis:latest

volumes:
  fusekidata:
