services:
  oteapi:
    image: ghcr.io/emmc-asbl/oteapi:1.20240301.346
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      OTEAPI_REDIS_TYPE: redis
      OTEAPI_REDIS_HOST: redis
      OTEAPI_REDIS_PORT: 6379
      OTEAPI_prefix: "${OTEAPI_prefix:-/api/v1}"
      OTEAPI_PLUGIN_PACKAGES: 'git+https://github.com/SINTEF/oteapi-dlite-Mod@master' # NOTE! Branch under development
      # OTEAPI_PLUGIN_PACKAGES: "-v -e /oteapi-dlite"
    volumes:
      - "./entities:/entities"
      - "./output:/output"
      # - "./oteapi-dlite:/oteapi-dlite"

  redis:
    image: redis:latest

  fuseki:
    image: secoresearch/fuseki
    container_name: fuseki
    ports:
      - "3030:3030"
    environment:
      ADMIN_PASSWORD: admin
    volumes:
      - fuseki_data:/fuseki

volumes:
  fuseki_data:
