version: "3.8"

services:

  oteapi:
    image: ghcr.io/emmc-asbl/oteapi:1.20240301.346
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      OTEAPI_REDIS_TYPE: redis
      OTEAPI_REDIS_HOST: redis
      OTEAPI_REDIS_PORT: 6379
      OTEAPI_prefix: "${OTEAPI_prefix:-/api/v1}"   
      OTEAPI_PLUGIN_PACKAGES: 'git+https://github.com/SINTEF/oteapi-dlite-Mod@master' # NOTE! Branch under development
    volumes:
      - "./entities:/entities"
      - "./output:/output"

  redis:
    image: redis:latest

